name: data-visualiser
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.10.9
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - contourpy==1.0.7
      - cycler==0.11.0
      - fonttools==4.38.0
      - kiwisolver==1.4.4
      - matplotlib==3.7.0
      - numpy==1.24.2
      - packaging==23.0
      - pandas==1.5.3
      - pillow==9.4.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - six==1.16.0
